### ISSUE TITLE
Public Task import

### ISSUE THREAD

**Issue by knownasilya** [machty/ember-concurrency#281] opened 2019-03-01 17:44 UTC
Currently I'm doing something like:

```js
import { Task } from 'ember-concurrency/-task-property';

export default class PitchDeckEditor extends Component {

  @argument(Task)
  updateProfileTask;
```

Would love to have a public import for `Task`, since it's documented in the API.

**Comment by maxfierke** [comment] 2019-08-08 04:02
Hi @knownasilya 👋 ! I'm going through and cleaning up the issue queue. It appears this is a duplicate of #123, so I'm going to close it out. However, it appears that this will be tackled by #302, if/when it gets merged.

**Closed by maxfierke** 2019-08-08 04:02 UTC
