### ISSUE TITLE
Task concurrency not updating when yielding an Ember Data promise

### ISSUE THREAD

**Issue by jeradg** [machty/ember-concurrency#26] opened 2016-03-04 20:09 UTC
I'm trying to use a task's `isRunning` property to show a spinner while a task is pending. (`isRunning` is computed based on the task's `concurrency` count.)

When I yield an ember-concurrency `timeout()`, or a promise that uses `setTimeout()`, the spinner behaves as expected. However, when I yield an Ember Data query (a promise), there is a delay before the spinner shows.

A strange workaround: If I put an additional `yield timeout(0);` before the actual promise I'm waiting for, the spinner spins as expected. (It doesn't matter what number I pass to `timeout()`.)

(I'm using mirage to fake the API responses, if that comes into play. The spinner does not spin while mirage's handlers are executing.)

Component template:

```hbs
<button {{action 'submit'}}>
  {{#if submitTask.isRunning}}
    Wait... <img src="spinner.gif">
  {{else}}
    Submit
  {{/if}}
</button>
```

## Works

This version of the component shows the spinner while the promise is not yet resolved:

```js
export default Ember.Component.extend({
  actions: {                                           
    submit() {                            
      this.get('submitTask').perform();
    }
  },

  submitTask: task(function * () {      
    yield timeout(1000);
  })                                           
});
```

This also shows the spinner:

```js
export default Ember.Component.extend({
  actions: {                                           
    submit() {                            
      this.get('submitTask').perform();
    }
  },

  submitTask: task(function * () {      
    yield new Ember.RSVP.Promise((resolve) => {    
      setTimeout(function() {
        resolve();
      }, 1000);
    });
  })                                           
});
```

Passing `yield timeout(0)` as a workaround:

```js
export default Ember.Component.extend({
  actions: {                                           
    submit() {                            
      this.get('submitTask').perform();
    }
  },

  submitTask: task(function * () {      
    yield timeout(0);
    yield this.get('store').query('thing', { whatever });
  })                                           
});
```

## Does not work

This does NOT show the spinner (the query still fires and gets the correct results):

```js
export default Ember.Component.extend({
  actions: {                                           
    submit() {                            
      this.get('submitTask').perform();
    }
  },

  submitTask: task(function * () {      
    yield this.get('store').query('thing', { whatever });
  })                                           
});
```

This also does NOT show the spinner (the query still fires and gets the correct results):

```js
export default Ember.Component.extend({
  actions: {                                           
    submit() {                            
      this.get('submitTask').perform();
    }
  },

  submitTask: task(function * () {      
    yield new Ember.RSVP.Promise((resolve) => {
      this.get('store').query('thing', { whatever })
        .then(() => resolve());
    });
  })                                           
});
```

**Comment by jeradg** [comment] 2016-03-04 22:25
Also:

**Comment by machty** [comment] 2016-03-07 01:59
I've been discussing this with @jeradg the past few days in the ember-concurrency channel in the embercommunity Slack, and we've determined that the root cause of this isn't actually a bug in e-c but is a run loop artifact that presents itself when testing behavior that seems async but completes within the same run loop.

In short, if a task completes within the same run loop, its `isRunning` property will flip to true and then back to false before the template even has a chance to render, any acceptance tests that assert against the DOM for loading spinners and the like aren't usable when using a stubbing library like ember-cli-mirage or pretender (which resolve within the same run loop by default) unless their handlers are made async.

The reason the `yield timeout(0)`s made the tests "pass" is that the timeout of 0 forced the task to complete on the next run loop, which allowed the DOM to render loading UI behind `{{#if isRunning}}`.

I'll keep this issue in mind while amassing ideas for adding documentation for testing, but there isn't actually a bug here, so, closing the issue.

**Closed by machty** 2016-03-07 01:59 UTC

**Comment by jasonmit** [comment] 2016-09-07 23:30
I'm also seeing this w/o the presense of mirage and oddly it works with native Promises (i.e `Promise.reject()`) but fails with `RSVP.reject()`
