### ISSUE TITLE
Does not work with native classes

### ISSUE THREAD

**Issue by mfeckie** [machty/ember-concurrency#271] opened 2019-01-16 12:59 UTC
Using Ember 3.6, ember-concurrency 0.8.26

Given a component defined with 'classic' syntax, all is good.

```js
import Component from '@ember/component'
import { task, timeout } from 'ember-concurrency';

export default Component.extend({
  result: null,
  doStuff: task(function*(){
    yield timeout(1000);
    this.set('result', 'done');
  })
});
```

If, however, we use native class syntax

```js
import Component from '@ember/component';
import { task, timeout } from 'ember-concurrency';

export default class NativeTaskComponent extends Component {
  result = null;
  doStuff = task(function*() {
    yield timeout(1000);
    this.set('result', new Date());
  });
}
```

We see `-task-property.js:620 Uncaught Error: It looks like you tried to perform a task via this.nameOfTask.perform(), which isn't supported. Use 'this.get('nameOfTask').perform()' instead.`

I've spent a little time trying to figure out why this is the case and have found that when creating a TaskProperty, the function passed to `super` does not get executed https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L416-L437

```js
export class TaskProperty extends _ComputedProperty {
  constructor(taskFn) {
    let tp;
    console.log('called before super');
    super(function(_propertyName) {
      console.log('called inside super anonymous function');
      taskFn.displayName = `${_propertyName} (task)`;
...
```

The transpiled output of the classic invocation is

```js
define("dummy/components/classic-task/component", ["exports", "ember-concurrency"], function (_exports, _emberConcurrency) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  var _default = Ember.Component.extend({
    result: null,
    doStuff: (0, _emberConcurrency.task)(function* () {
      yield (0, _emberConcurrency.timeout)(1000);
      this.set('result', 'done');
    })
  });

  _exports.default = _default;
});
```

Whilst the native version is

```js
define("dummy/components/native-task/component", ["exports", "ember-concurrency"], function (_exports, _emberConcurrency) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

  class NativeTaskComponent extends Ember.Component {
    constructor(...args) {
      super(...args);

      _defineProperty(this, "result", null);

      _defineProperty(this, "doStuff", (0, _emberConcurrency.task)(function* () {
        yield (0, _emberConcurrency.timeout)(1000);
        this.set('result', new Date());
      }));
    }

  }

  _exports.default = NativeTaskComponent;
});
```

So it looks like it's caused by the way the property ends up being defined on the native class that is causing the issue.

**Comment by buschtoens** [comment] 2019-01-16 13:00
Duplicate of https://github.com/machty/ember-concurrency/issues/241

**Comment by buschtoens** [comment] 2019-01-16 13:09
The three solutions are:

- define task in `.extend({ })` block, like
  ```ts
  class extends Component.extend({
    myTask: task(function*() {}),
  }) {
    // rest of the class body
  }
  ```
- use `defineProperty`, which has performance implications
- use ember-concurrency-decorators, for which I need to update the type definitons

**Comment by machty** [comment] 2019-01-16 13:52
Totally agree that this needs to be documented, as I always forget what the rules are myself. Would also appreciate a section in the doc on what the rules/options are for TypeScript. I'm very busy lately (and also a tad rusty) so I'd very much welcome a docs PR on this stuff.

**Comment by crhayes** [comment] 2019-01-17 00:01
@aaronbhansen I am experiencing the same thing after moving from Ember 3.5 --> Ember 3.6. During this process I was upgraded from Babel 6 --> Babel 7. Could this be part of the issue?

**Comment by Aaronfischer** [comment] 2019-01-17 00:04
@crhayes After some random shots in the dark, I made sure that ember-concurrency was running X.X.26, which required upgrading other dependencies (like ember-power-select and an internal add-on we maintain), did this looking within `yarn.lock`.
This "seems" to have resolved the issue, I haven't been able to fully test yet, but it did remove the error on application load.

**Comment by buschtoens** [comment] 2019-01-17 00:07
Pretty sure you are running into #262 and #265, which is why making sure you are on the latest version of ember-concurrency fixed it. :blush:

**Comment by buschtoens** [comment] 2019-04-01 07:11
For completeness sake: In the Octane edition of Ember.js, you can create a task like this:

```js
class MyClass {
  @task(function*() {
    // ...
  } myTask;
}
```

**Comment by gabrielgrant** [comment] 2019-07-24 16:15
@buschtoens i think you're maybe missing a closing paren?

```
class MyClass {
  @task(function*() {
    // ...
  }) myTask;  // <-- note closing paren on this line
}
```

**Comment by buschtoens** [comment] 2019-07-25 08:00
@gabrielgrant That is correct, thanks! I updated the snippet. :)

**Comment by BryanCrotaz** [comment] 2019-08-02 21:30
What’s the correct syntax for using typescript with ember 3.11?

**Comment by buschtoens** [comment] 2019-08-05 08:49
@BryanCrotaz The issue is that decorators cannot (yet) influence the type signature. To circumvent this, I made [`ember-concurrency-typescript`](https://github.com/buschtoens/ember-concurrency-typescript#readme), but it's not fully done yet: https://github.com/buschtoens/ember-concurrency-typescript/issues/6

**Comment by jenweber** [comment] 2019-11-01 15:19
Could we start by adding an example to the Task Function Syntax page? Or do we also need to cover the caveats/edge cases for it to be merged?

Example gist: https://gist.github.com/jenweber/443dac9876c7ef2b1115093cfd5d6fac

**Comment by buschtoens** [comment] 2019-11-01 16:02
I'd support adding the `@task(function*() {})` syntax to the official docs, as @jenweber suggested.

We can also mention `ember-concurrency-decorators` as an alternative. Related: #326

**Comment by maxfierke** [comment] 2019-11-25 04:40
Closing this out, since documentation has been added on using with native classes on Ember 3.10+. More specific issues w/ native classes, decorators, etc. can be addressed in separate issues as needed in the future.

**Closed by maxfierke** 2019-11-25 04:40 UTC
Labels: docs, ember-octane
