### ISSUE TITLE
Errors from subtasks are re-thrown even when caught

### ISSUE THREAD

**Issue by dfreeman** [machty/ember-concurrency#42] opened 2016-04-08 15:27 UTC
I believe @wecc mentioned seeing something like this in Slack as well, but I didn't see an issue already filed here. If I perform `task` below, the resulting error hits the `catch` block, but it also ends up being rethrown elsewhere and trickling up to `window.onerror`.

```js
task: task(function* () {
  try {
    yield this.get('subtask').perform();
  } catch (error) {
    console.log('caught', error);
  }
}),

subtask: task(function* () {
  throw new Error('boom');
})
```

![image](https://cloud.githubusercontent.com/assets/108688/14388603/e125268a-fd7c-11e5-83af-369962b10256.png)

**Comment by machty** [comment] 2016-04-08 16:08
Ah I see what the problem is... right now e-c only considers errors "caught" if you call `.then``.catch` on the task instance, but catching in the catch block of a parent task presently isn't being handled. 

Should have a fix for this soon.

**Comment by wecc** [comment] 2016-04-26 17:55
At first I didn't think our scenario was the same as this one but then (well, just now) I realized that the double-thrown-error thing only occurred when we saved stuff in modals, and yeah, we pass a task to our modals and our modals has their own task that performs the provided task. So our issue is indeed exactly the same parent/sub-task thing described above.

**Comment by wecc** [comment] 2016-04-26 17:58
...well, except we don't catch anything in the parent task so our error is thrown twice.

**Comment by wecc** [comment] 2016-04-26 18:06
Sorry for rubber ducking here but I've successfully created a reproduction at https://canary.ember-twiddle.com/3f06ac7ae7accc397a171b494b9b0f64?openFiles=application.controller.js

(for some reason I can't click but have to tab to the `perform` button)

**Comment by machty** [comment] 2016-04-27 16:07
Fixed and release in 0.6.2

**Comment by dfreeman** [comment] 2016-04-28 14:56
It looks like this is solved for direct descendants, but if the handler is more than one task "layer" away, I'm still seeing `window.onerror` get triggered in [this twiddle with 0.6.2](https://canary.ember-twiddle.com/130267a61de6e60da9587293999f320a?fileTreeShown=false&numColumns=2&openFiles=twiddle.json%2Ccontrollers.application.js).

**Comment by machty** [comment] 2016-04-28 15:41
@dfreeman yeah, I see it too, and @wecc reported in the Slack channel that if you don't catch an error, you get double error reports. I have an idea for how to fix, will tackle shortly.

**Comment by machty** [comment] 2016-05-01 12:02
@wecc @dfreeman could you please try out the `double-error-fix` branch to see if this problem's finally fixed?

**Comment by dfreeman** [comment] 2016-05-02 00:49
@machty That looks like it did the trick! (...and uncovered a small bug in our global error handler, too)

**Closed** 2016-05-02 17:02 UTC

**Comment by wecc** [comment] 2016-05-03 16:20
Sorry for the late response – confirming that 0.6.3 solves the issue in our app! ❤️
